services:
  gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5011
    ports:
      - "5011:5011"
    networks:
      - backendservice_network

  api1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
    ports:
      - "5001:5001"
    networks:
      - backendservice_network
    depends_on: 
      - gateway
      - rabbitmq
      - consul

  api2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
    ports:
      - "5002:5002"
    networks:
      - backendservice_network
    depends_on: 
      - gateway
      - rabbitmq
      - consul

  consul:
    ports:
      - 8500:8500
      - 8600:8600/tcp
      - 8600:8600/udp
    networks:
      - backendservice_network
  
  rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - backendservice_network

networks:
  backendservice_network:
     driver: bridge
     external: true

volumes:
 rabbitmq:


 